pipeline{
    agent any
   
    tools { 
        maven 'Maven'
      
    }
        stages{
            stage('Git-Checkout')
            {
                steps{
                     git 'https://github.com/sreelakshmi665/HelloWorld.git'
                }
            }
             stage('Clean')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml clean'
            }
        }
            
             stage('Validate')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml validate'
            }
        }
        stage('Compile')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml compile'
            }
        }
        stage('sonar analysis'){
            steps{
                withSonarQubeEnv('sonar-server'){
                    withMaven(maven:'Maven'){
                        bat 'mvn -f HelloWorld/pom.xml sonar:sonar'
                    }
                }
            }

        }
        stage('Test')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml test'
            }
        }
        stage('Package')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml package'
            }
        }
        stage('Verify')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml verify'
            }
        }
        stage('Install')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml install'
            }
        }
            stage('Artifactory')
    {
      steps{
        archiveArtifacts artifacts:'HelloWorld/target/*.jar',followSymlinks:false
      }
    }
    stage('Deploy-To-Artifactory')
    {
      steps{
        rtUpload(
          serverId:'artifactory-server',
          spec: '''{
          "files": [
            {
              "pattern": "HelloWorld/target/*.jar",
              "target": "art-doc-dev-loc"
            }
         ]
    }''',
           buildName: 'holyFrog',
    buildNumber: '42'
)
  }
}
            
            
           
        }
}
