pipeline{
    agent any
   
    tools { 
        maven 'Maven'
      
    }
        stages{
            stage('Git-Checkout')
            {
                steps{
                     git 'https://github.com/sreelakshmi665/HelloWorld.git'
                }
            }
             stage('Validate')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml validate'
            }
        }
        stage('Compile')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml compile'
            }
        }
        stage('sonar analysis'){
            steps{
                withSonarQubeEnv('sonar-server'){
                    withMaven(maven:'Maven'){
                        bat 'mvn sonar:sonar'
                    }
                }
            }

        }
        stage('Test')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml test'
            }
        }
        stage('Package')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml package'
            }
        }
        stage('Verify')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml verify'
            }
        }
        stage('Install')
        {
            steps{
                bat 'mvn -f HelloWorld/pom.xml install'
            }
        }
            
            
           
        }
}
